<a href="https://colab.research.google.com/github/mipaillafil/Proyecto_Aeropuertos_Cortes_Marchesse_Paillafil/blob/main/Evaluacion_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Importaciones
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [4]:
#Cargar dataset sucio
url = "https://raw.githubusercontent.com/mipaillafil/Proyecto_Aeropuertos_Cortes_Marchesse_Paillafil/main/data/operaciones_aeropuertos_dirty.csv"
df = pd.read_csv(url)
df.head()

     mes_id aeropuerto_oaci internacional_domestico cnt_operaciones
0  200001.0            SCAP                     D               6.0
1  200001.0            SCAR                       D           691.0
2  200001.0            SCAR                       I         139.0
3  200001.0            SCBA                       D         382.0
4  200001.0            SCCC                       D            82.0

In [6]:
#Analisis inicial
#Mostrar estructura general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16507 entries, 0 to 16506
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mes_id                   15712 non-null  object
 1   aeropuerto_oaci          15725 non-null  object
 2   internacional_domestico  15716 non-null  object
 3   cnt_operaciones          15739 non-null  object
dtypes: object(4)
memory usage: 516.0+ KB

In [7]:
#Identificar la cantidad de valores nulos que hay en cada columna
df.isnull().sum()

mes_id                     795
aeropuerto_oaci            782
internacional_domestico    791
cnt_operaciones            768
dtype: int64

In [8]:
#Estadisticas de la variables númericas para detectar posibles outliers.
df.describe()

          mes_id aeropuerto_oaci internacional_domestico cnt_operaciones
count      15712           15725                   15716           15739
unique       604             120                       5            3125
top     202412.0            SCEL                       D             2.0
freq          67             615                   11143             602

In [10]:
#Copiar dataset
df_sucio = df.copy()
df_sucio.head()

     mes_id aeropuerto_oaci internacional_domestico cnt_operaciones
0  200001.0            SCAP                     D               6.0
1  200001.0            SCAR                       D           691.0
2  200001.0            SCAR                       I         139.0
3  200001.0            SCBA                       D         382.0
4  200001.0            SCCC                       D            82.0

In [12]:
#Limpieza base
#Eliminar datos duplicados
df_sucio = df_sucio.drop_duplicates()

# Limpiar espacios en strings
df_sucio = df_sucio.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [13]:
#Separación por tipo de variable
num_cols = df_sucio.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = df_sucio.select_dtypes(include=['object']).columns.tolist()

In [ ]:
#Pipeline númerico
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])